# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 13:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(db_column='job_id', primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=15000, null=True, verbose_name='Descrição')),
                ('value', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True, verbose_name='Valor')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
        ),
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.AutoField(db_column='job_type_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_type', to='workshop.JobType'),
        ),
    ]
