# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtype',
            name='description',
            field=models.CharField(blank=True, max_length=15000, null=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='jobtype',
            name='slug_name',
            field=models.SlugField(default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_type', to='workshop.JobType', verbose_name='Tipo'),
        ),
    ]
